# HTTP Server (Tomcat) Port
server: 
  port: 8089
  forward-headers-strategy: framework
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
  
error:
  whitelabel:
    enabled: true

spring:
   application:
     name: unlimits_docs
   main:
     allow-bean-definition-overriding: true

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: http://51.79.159.7:8080/auth/v3/api-docs
        name: unlimits_auth
        primaryName: unlimits_auth
      - url: http://51.79.159.7:8080/content/v3/api-docs
        name: unlimits_content
        primaryName: unlimits_content
      - url: http://51.79.159.7:8080/integration/v3/api-docs
        name: unlimits_integration
        primaryName: unlimits_integration
      - url: http://51.79.159.7:8080/client/v3/api-docs
        name: unlimits_client
        primaryName: unlimits_client
openapi:
  service:
    title: docs
    version: 1.0.0
    url: http://51.79.159.7:8089
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/       