spring:
   config:
     activate:
      on-profile: local
   application:
     name: unlimits_docs
   main:
     allow-bean-definition-overriding: true
server: 
  host: 51.79.159.7
  port: 9091
  resource:
    location: file:C:/app_runs/unlimits-resources/resource
  gateway:
    host: 51.79.159.7
    port: 8081
    endpoint: docs
  eureka:
    host: 51.79.159.7
    port: 1001 
error:
  whitelabel:
    enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: http://${server.gateway.host}:${server.gateway.port}/auth/v3/api-docs
        name: unlimits_auth
        primaryName: unlimits_auth
      - url: http://${server.gateway.host}:${server.gateway.port}/content/v3/api-docs
        name: unlimits_content
        primaryName: unlimits_content
      - url: http://${server.gateway.host}:${server.gateway.port}/integration/v3/api-docs
        name: unlimits_integration
        primaryName: unlimits_integration
      - url: http://${server.gateway.host}:${server.gateway.port}/client/v3/api-docs
        name: unlimits_client
        primaryName: unlimits_client
openapi:
  service:
    title: docs
    version: 1.0.0
    url: http://${server.gateway.host}:${server.gateway.port} #api gateway url
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://${server.eureka.host}:${server.eureka.port}/eureka/
---
spring:
   config:
     activate:
      on-profile: develop
   application:
     name: unlimits_docs
   main:
     allow-bean-definition-overriding: true
server: 
  host: 51.79.159.7
  port: 9092
  resource:
    location: file:C:/app_runs/unlimits-resources/resource
  gateway:
    host: 51.79.159.7
    port: 8082
    endpoint: docs
  eureka:
    host: 51.79.159.7
    port: 1002 
error:
  whitelabel:
    enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: http://${server.gateway.host}:${server.gateway.port}/auth/v3/api-docs
        name: unlimits_auth
        primaryName: unlimits_auth
      - url: http://${server.gateway.host}:${server.gateway.port}/content/v3/api-docs
        name: unlimits_content
        primaryName: unlimits_content
      - url: http://${server.gateway.host}:${server.gateway.port}/integration/v3/api-docs
        name: unlimits_integration
        primaryName: unlimits_integration
      - url: http://${server.gateway.host}:${server.gateway.port}/client/v3/api-docs
        name: unlimits_client
        primaryName: unlimits_client
openapi:
  service:
    title: docs
    version: 1.0.0
    url: http://${server.gateway.host}:${server.gateway.port} #api gateway url
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://${server.eureka.host}:${server.eureka.port}/eureka/
---
spring:
   config:
     activate:
      on-profile: stage
   application:
     name: unlimits_docs
   main:
     allow-bean-definition-overriding: true
server: 
  host: 51.79.159.7
  port: 9093
  resource:
    location: file:C:/app_runs/unlimits-resources/resource
  gateway:
    host: 51.79.159.7
    port: 8083
    endpoint: docs
  eureka:
    host: 51.79.159.7
    port: 1003 
error:
  whitelabel:
    enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: http://${server.gateway.host}:${server.gateway.port}/auth/v3/api-docs
        name: unlimits_auth
        primaryName: unlimits_auth
      - url: http://${server.gateway.host}:${server.gateway.port}/content/v3/api-docs
        name: unlimits_content
        primaryName: unlimits_content
      - url: http://${server.gateway.host}:${server.gateway.port}/integration/v3/api-docs
        name: unlimits_integration
        primaryName: unlimits_integration
      - url: http://${server.gateway.host}:${server.gateway.port}/client/v3/api-docs
        name: unlimits_client
        primaryName: unlimits_client
openapi:
  service:
    title: docs
    version: 1.0.0
    url: http://${server.gateway.host}:${server.gateway.port}/${server.gateway.endpoint} #api gateway url   
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://${server.eureka.host}:${server.eureka.port}/eureka/